# Generated by Django 4.2.9 on 2024-01-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('diretor', models.CharField(max_length=60)),
                ('sinopse', models.TextField()),
                ('ano_lancamento', models.DateField()),
                ('duracao', models.IntegerField(default=0)),
                ('genero', models.CharField(choices=[('AC', 'Ação'), ('AV', 'Aventura'), ('RO', 'Romance'), ('TE', 'Terror'), ('DR', 'Drama'), ('SU', 'Suspense'), ('FC', 'Ficção Cientifica'), ('DO', 'Documentario'), ('AN', 'Animação'), ('NS', 'Não Selecionado')], default='NS', max_length=2)),
                ('dat_cad', models.DateField(auto_now_add=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='capas')),
            ],
        ),
    ]
