# Generated by Django 4.2.9 on 2024-01-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.FloatField()),
                ('hora', models.TimeField()),
                ('dat_con', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
